table DimProduct

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey

	column Product
		dataType: string
		summarizeBy: none
		sourceColumn: Product

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category

	partition DimProduct = m
		mode: import
		source =
			let
			    Source = Table.FromRows({
			        {1, "Cloud Services", "Recurring"},
			        {2, "Licensing", "Recurring"},
			        {3, "Consulting", "Services"},
			        {4, "Hardware", "Product"},
			        {5, "Support", "Services"}
			    }, {"ProductKey", "Product", "Category"}),
			    Typed = Table.TransformColumnTypes(Source, {{"ProductKey", Int64.Type}, {"Product", type text}, {"Category", type text}})
			in
			    Typed
