table FactPlan

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: Date

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey

	column RegionKey
		dataType: int64
		summarizeBy: none
		sourceColumn: RegionKey

	column Amount
		dataType: double
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Amount

	partition FactPlan = m
		mode: import
		source =
			let
			    Source = Table.FromRows({
			        {#date(2025,1,1), 1, 1, 1497888.97},
			        {#date(2025,1,1), 1, 2, 1048522.28},
			        {#date(2025,1,1), 1, 3, 748944.48},
			        {#date(2025,1,1), 1, 4, 449366.69},
			        {#date(2025,2,1), 1, 1, 1512034.74},
			        {#date(2025,2,1), 1, 2, 1058424.32},
			        {#date(2025,2,1), 1, 3, 756017.37},
			        {#date(2025,2,1), 1, 4, 453610.42},
			        {#date(2025,3,1), 1, 1, 1579900.28},
			        {#date(2025,3,1), 1, 2, 1105930.20},
			        {#date(2025,3,1), 1, 3, 789950.14},
			        {#date(2025,3,1), 1, 4, 473970.08},
			        {#date(2025,4,1), 1, 1, 1539311.53},
			        {#date(2025,4,1), 1, 2, 1077518.07},
			        {#date(2025,4,1), 1, 3, 769655.76},
			        {#date(2025,4,1), 1, 4, 461793.46},
			        {#date(2025,5,1), 1, 1, 1618768.85},
			        {#date(2025,5,1), 1, 2, 1133138.20},
			        {#date(2025,5,1), 1, 3, 809384.43},
			        {#date(2025,5,1), 1, 4, 485630.66},
			        {#date(2025,6,1), 1, 1, 1583820.64},
			        {#date(2025,6,1), 1, 2, 1108674.45},
			        {#date(2025,6,1), 1, 3, 791910.32},
			        {#date(2025,6,1), 1, 4, 475146.19},
			        {#date(2025,7,1), 1, 1, 1468752.16},
			        {#date(2025,7,1), 1, 2, 1028126.51},
			        {#date(2025,7,1), 1, 3, 734376.08},
			        {#date(2025,7,1), 1, 4, 440625.65},
			        {#date(2025,8,1), 1, 1, 1411960.64},
			        {#date(2025,8,1), 1, 2, 988372.45},
			        {#date(2025,8,1), 1, 3, 705980.32},
			        {#date(2025,8,1), 1, 4, 423588.19},
			        {#date(2025,9,1), 1, 1, 1636990.95},
			        {#date(2025,9,1), 1, 2, 1145893.66},
			        {#date(2025,9,1), 1, 3, 818495.47},
			        {#date(2025,9,1), 1, 4, 491097.28},
			        {#date(2025,10,1), 1, 1, 1691094.85},
			        {#date(2025,10,1), 1, 2, 1183766.40},
			        {#date(2025,10,1), 1, 3, 845547.43},
			        {#date(2025,10,1), 1, 4, 507328.46},
			        {#date(2025,11,1), 1, 1, 1746520.31},
			        {#date(2025,11,1), 1, 2, 1222564.22},
			        {#date(2025,11,1), 1, 3, 873260.16},
			        {#date(2025,11,1), 1, 4, 523956.09},
			        {#date(2025,12,1), 1, 1, 1845615.93},
			        {#date(2025,12,1), 1, 2, 1291931.15},
			        {#date(2025,12,1), 1, 3, 922807.96},
			        {#date(2025,12,1), 1, 4, 553684.78},
			        {#date(2025,1,1), 2, 1, 1205925.99},
			        {#date(2025,1,1), 2, 2, 844148.19},
			        {#date(2025,1,1), 2, 3, 602963.00},
			        {#date(2025,1,1), 2, 4, 361777.80},
			        {#date(2025,2,1), 2, 1, 1211846.95},
			        {#date(2025,2,1), 2, 2, 848292.86},
			        {#date(2025,2,1), 2, 3, 605923.47},
			        {#date(2025,2,1), 2, 4, 363554.08},
			        {#date(2025,3,1), 2, 1, 1293067.98},
			        {#date(2025,3,1), 2, 2, 905147.58},
			        {#date(2025,3,1), 2, 3, 646533.99},
			        {#date(2025,3,1), 2, 4, 387920.39},
			        {#date(2025,4,1), 2, 1, 1294321.84},
			        {#date(2025,4,1), 2, 2, 906025.28},
			        {#date(2025,4,1), 2, 3, 647160.92},
			        {#date(2025,4,1), 2, 4, 388296.55},
			        {#date(2025,5,1), 2, 1, 1370919.05},
			        {#date(2025,5,1), 2, 2, 959643.34},
			        {#date(2025,5,1), 2, 3, 685459.53},
			        {#date(2025,5,1), 2, 4, 411275.72},
			        {#date(2025,6,1), 2, 1, 1317124.26},
			        {#date(2025,6,1), 2, 2, 921986.98},
			        {#date(2025,6,1), 2, 3, 658562.13},
			        {#date(2025,6,1), 2, 4, 395137.28},
			        {#date(2025,7,1), 2, 1, 1189260.77},
			        {#date(2025,7,1), 2, 2, 832482.54},
			        {#date(2025,7,1), 2, 3, 594630.38},
			        {#date(2025,7,1), 2, 4, 356778.23},
			        {#date(2025,8,1), 2, 1, 1129885.18},
			        {#date(2025,8,1), 2, 2, 790919.63},
			        {#date(2025,8,1), 2, 3, 564942.59},
			        {#date(2025,8,1), 2, 4, 338965.56},
			        {#date(2025,9,1), 2, 1, 1329410.93},
			        {#date(2025,9,1), 2, 2, 930587.65},
			        {#date(2025,9,1), 2, 3, 664705.46},
			        {#date(2025,9,1), 2, 4, 398823.28},
			        {#date(2025,10,1), 2, 1, 1412677.30},
			        {#date(2025,10,1), 2, 2, 988874.11},
			        {#date(2025,10,1), 2, 3, 706338.65},
			        {#date(2025,10,1), 2, 4, 423803.19},
			        {#date(2025,11,1), 2, 1, 1480321.94},
			        {#date(2025,11,1), 2, 2, 1036225.36},
			        {#date(2025,11,1), 2, 3, 740160.97},
			        {#date(2025,11,1), 2, 4, 444096.58},
			        {#date(2025,12,1), 2, 1, 1545661.24},
			        {#date(2025,12,1), 2, 2, 1081962.87},
			        {#date(2025,12,1), 2, 3, 772830.62},
			        {#date(2025,12,1), 2, 4, 463698.37},
			        {#date(2025,1,1), 3, 1, 791878.68},
			        {#date(2025,1,1), 3, 2, 554315.08},
			        {#date(2025,1,1), 3, 3, 395939.34},
			        {#date(2025,1,1), 3, 4, 237563.60},
			        {#date(2025,2,1), 3, 1, 812627.37},
			        {#date(2025,2,1), 3, 2, 568839.16},
			        {#date(2025,2,1), 3, 3, 406313.68},
			        {#date(2025,2,1), 3, 4, 243788.21},
			        {#date(2025,3,1), 3, 1, 890818.25},
			        {#date(2025,3,1), 3, 2, 623572.77},
			        {#date(2025,3,1), 3, 3, 445409.12},
			        {#date(2025,3,1), 3, 4, 267245.47},
			        {#date(2025,4,1), 3, 1, 898092.86},
			        {#date(2025,4,1), 3, 2, 628665.00},
			        {#date(2025,4,1), 3, 3, 449046.43},
			        {#date(2025,4,1), 3, 4, 269427.86},
			        {#date(2025,5,1), 3, 1, 934081.03},
			        {#date(2025,5,1), 3, 2, 653856.72},
			        {#date(2025,5,1), 3, 3, 467040.52},
			        {#date(2025,5,1), 3, 4, 280224.31},
			        {#date(2025,6,1), 3, 1, 873790.49},
			        {#date(2025,6,1), 3, 2, 611653.34},
			        {#date(2025,6,1), 3, 3, 436895.24},
			        {#date(2025,6,1), 3, 4, 262137.15},
			        {#date(2025,7,1), 3, 1, 779723.83},
			        {#date(2025,7,1), 3, 2, 545806.68},
			        {#date(2025,7,1), 3, 3, 389861.91},
			        {#date(2025,7,1), 3, 4, 233917.15},
			        {#date(2025,8,1), 3, 1, 751794.72},
			        {#date(2025,8,1), 3, 2, 526256.31},
			        {#date(2025,8,1), 3, 3, 375897.36},
			        {#date(2025,8,1), 3, 4, 225538.42},
			        {#date(2025,9,1), 3, 1, 909884.44},
			        {#date(2025,9,1), 3, 2, 636919.11},
			        {#date(2025,9,1), 3, 3, 454942.22},
			        {#date(2025,9,1), 3, 4, 272965.33},
			        {#date(2025,10,1), 3, 1, 981019.17},
			        {#date(2025,10,1), 3, 2, 686713.42},
			        {#date(2025,10,1), 3, 3, 490509.58},
			        {#date(2025,10,1), 3, 4, 294305.75},
			        {#date(2025,11,1), 3, 1, 1015736.73},
			        {#date(2025,11,1), 3, 2, 711015.71},
			        {#date(2025,11,1), 3, 3, 507868.36},
			        {#date(2025,11,1), 3, 4, 304721.02},
			        {#date(2025,12,1), 3, 1, 1032603.24},
			        {#date(2025,12,1), 3, 2, 722822.27},
			        {#date(2025,12,1), 3, 3, 516301.62},
			        {#date(2025,12,1), 3, 4, 309780.97},
			        {#date(2025,1,1), 4, 1, 621588.65},
			        {#date(2025,1,1), 4, 2, 435112.06},
			        {#date(2025,1,1), 4, 3, 310794.33},
			        {#date(2025,1,1), 4, 4, 186476.60},
			        {#date(2025,2,1), 4, 1, 655329.85},
			        {#date(2025,2,1), 4, 2, 458730.89},
			        {#date(2025,2,1), 4, 3, 327664.92},
			        {#date(2025,2,1), 4, 4, 196598.95},
			        {#date(2025,3,1), 4, 1, 723550.46},
			        {#date(2025,3,1), 4, 2, 506485.32},
			        {#date(2025,3,1), 4, 3, 361775.23},
			        {#date(2025,3,1), 4, 4, 217065.14},
			        {#date(2025,4,1), 4, 1, 716299.65},
			        {#date(2025,4,1), 4, 2, 501409.76},
			        {#date(2025,4,1), 4, 3, 358149.83},
			        {#date(2025,4,1), 4, 4, 214889.90},
			        {#date(2025,5,1), 4, 1, 725380.49},
			        {#date(2025,5,1), 4, 2, 507766.35},
			        {#date(2025,5,1), 4, 3, 362690.25},
			        {#date(2025,5,1), 4, 4, 217614.15},
			        {#date(2025,6,1), 4, 1, 670612.72},
			        {#date(2025,6,1), 4, 2, 469428.90},
			        {#date(2025,6,1), 4, 3, 335306.36},
			        {#date(2025,6,1), 4, 4, 201183.81},
			        {#date(2025,7,1), 4, 1, 607304.53},
			        {#date(2025,7,1), 4, 2, 425113.17},
			        {#date(2025,7,1), 4, 3, 303652.27},
			        {#date(2025,7,1), 4, 4, 182191.36},
			        {#date(2025,8,1), 4, 1, 602319.63},
			        {#date(2025,8,1), 4, 2, 421623.74},
			        {#date(2025,8,1), 4, 3, 301159.82},
			        {#date(2025,8,1), 4, 4, 180695.89},
			        {#date(2025,9,1), 4, 1, 739641.92},
			        {#date(2025,9,1), 4, 2, 517749.34},
			        {#date(2025,9,1), 4, 3, 369820.96},
			        {#date(2025,9,1), 4, 4, 221892.58},
			        {#date(2025,10,1), 4, 1, 787958.29},
			        {#date(2025,10,1), 4, 2, 551570.80},
			        {#date(2025,10,1), 4, 3, 393979.15},
			        {#date(2025,10,1), 4, 4, 236387.49},
			        {#date(2025,11,1), 4, 1, 794330.21},
			        {#date(2025,11,1), 4, 2, 556031.14},
			        {#date(2025,11,1), 4, 3, 397165.10},
			        {#date(2025,11,1), 4, 4, 238299.06},
			        {#date(2025,12,1), 4, 1, 793090.32},
			        {#date(2025,12,1), 4, 2, 555163.22},
			        {#date(2025,12,1), 4, 3, 396545.16},
			        {#date(2025,12,1), 4, 4, 237927.10},
			        {#date(2025,1,1), 5, 1, 325172.01},
			        {#date(2025,1,1), 5, 2, 227620.41},
			        {#date(2025,1,1), 5, 3, 162586.00},
			        {#date(2025,1,1), 5, 4, 97551.60},
			        {#date(2025,2,1), 5, 1, 345287.80},
			        {#date(2025,2,1), 5, 2, 241701.46},
			        {#date(2025,2,1), 5, 3, 172643.90},
			        {#date(2025,2,1), 5, 4, 103586.34},
			        {#date(2025,3,1), 5, 1, 374355.22},
			        {#date(2025,3,1), 5, 2, 262048.65},
			        {#date(2025,3,1), 5, 3, 187177.61},
			        {#date(2025,3,1), 5, 4, 112306.57},
			        {#date(2025,4,1), 5, 1, 360842.46},
			        {#date(2025,4,1), 5, 2, 252589.72},
			        {#date(2025,4,1), 5, 3, 180421.23},
			        {#date(2025,4,1), 5, 4, 108252.74},
			        {#date(2025,5,1), 5, 1, 361136.94},
			        {#date(2025,5,1), 5, 2, 252795.86},
			        {#date(2025,5,1), 5, 3, 180568.47},
			        {#date(2025,5,1), 5, 4, 108341.08},
			        {#date(2025,6,1), 5, 1, 338827.83},
			        {#date(2025,6,1), 5, 2, 237179.48},
			        {#date(2025,6,1), 5, 3, 169413.91},
			        {#date(2025,6,1), 5, 4, 101648.35},
			        {#date(2025,7,1), 5, 1, 315628.23},
			        {#date(2025,7,1), 5, 2, 220939.76},
			        {#date(2025,7,1), 5, 3, 157814.11},
			        {#date(2025,7,1), 5, 4, 94688.47},
			        {#date(2025,8,1), 5, 1, 317617.10},
			        {#date(2025,8,1), 5, 2, 222331.97},
			        {#date(2025,8,1), 5, 3, 158808.55},
			        {#date(2025,8,1), 5, 4, 95285.13},
			        {#date(2025,9,1), 5, 1, 385379.69},
			        {#date(2025,9,1), 5, 2, 269765.78},
			        {#date(2025,9,1), 5, 3, 192689.85},
			        {#date(2025,9,1), 5, 4, 115613.91},
			        {#date(2025,10,1), 5, 1, 399728.14},
			        {#date(2025,10,1), 5, 2, 279809.70},
			        {#date(2025,10,1), 5, 3, 199864.07},
			        {#date(2025,10,1), 5, 4, 119918.44},
			        {#date(2025,11,1), 5, 1, 395759.92},
			        {#date(2025,11,1), 5, 2, 277031.95},
			        {#date(2025,11,1), 5, 3, 197879.96},
			        {#date(2025,11,1), 5, 4, 118727.98},
			        {#date(2025,12,1), 5, 1, 398078.66},
			        {#date(2025,12,1), 5, 2, 278655.06},
			        {#date(2025,12,1), 5, 3, 199039.33},
			        {#date(2025,12,1), 5, 4, 119423.60}
			    }, {"Date", "ProductKey", "RegionKey", "Amount"}),
			    Typed = Table.TransformColumnTypes(Source, {{"Date", type date}, {"ProductKey", Int64.Type}, {"RegionKey", Int64.Type}, {"Amount", type number}})
			in
			    Typed
