table FactBudget

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: Date

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey

	column RegionKey
		dataType: int64
		summarizeBy: none
		sourceColumn: RegionKey

	column Amount
		dataType: double
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Amount

	partition FactBudget = m
		mode: import
		source =
			let
			    Source = Table.FromRows({
			        {#date(2025,1,1), 1, 1, 1526694.52},
			        {#date(2025,1,1), 1, 2, 1068686.17},
			        {#date(2025,1,1), 1, 3, 763347.26},
			        {#date(2025,1,1), 1, 4, 458008.36},
			        {#date(2025,2,1), 1, 1, 1541112.33},
			        {#date(2025,2,1), 1, 2, 1078778.63},
			        {#date(2025,2,1), 1, 3, 770556.17},
			        {#date(2025,2,1), 1, 4, 462333.70},
			        {#date(2025,3,1), 1, 1, 1610282.98},
			        {#date(2025,3,1), 1, 2, 1127198.08},
			        {#date(2025,3,1), 1, 3, 805141.49},
			        {#date(2025,3,1), 1, 4, 483084.89},
			        {#date(2025,4,1), 1, 1, 1568913.67},
			        {#date(2025,4,1), 1, 2, 1098239.57},
			        {#date(2025,4,1), 1, 3, 784456.83},
			        {#date(2025,4,1), 1, 4, 470674.10},
			        {#date(2025,5,1), 1, 1, 1649899.02},
			        {#date(2025,5,1), 1, 2, 1154929.32},
			        {#date(2025,5,1), 1, 3, 824949.51},
			        {#date(2025,5,1), 1, 4, 494969.71},
			        {#date(2025,6,1), 1, 1, 1614278.73},
			        {#date(2025,6,1), 1, 2, 1129995.11},
			        {#date(2025,6,1), 1, 3, 807139.37},
			        {#date(2025,6,1), 1, 4, 484283.62},
			        {#date(2025,7,1), 1, 1, 1496997.39},
			        {#date(2025,7,1), 1, 2, 1047898.18},
			        {#date(2025,7,1), 1, 3, 748498.70},
			        {#date(2025,7,1), 1, 4, 449099.22},
			        {#date(2025,8,1), 1, 1, 1439113.73},
			        {#date(2025,8,1), 1, 2, 1007379.61},
			        {#date(2025,8,1), 1, 3, 719556.86},
			        {#date(2025,8,1), 1, 4, 431734.12},
			        {#date(2025,9,1), 1, 1, 1668471.54},
			        {#date(2025,9,1), 1, 2, 1167930.08},
			        {#date(2025,9,1), 1, 3, 834235.77},
			        {#date(2025,9,1), 1, 4, 500541.46},
			        {#date(2025,10,1), 1, 1, 1723615.91},
			        {#date(2025,10,1), 1, 2, 1206531.13},
			        {#date(2025,10,1), 1, 3, 861807.95},
			        {#date(2025,10,1), 1, 4, 517084.77},
			        {#date(2025,11,1), 1, 1, 1780107.24},
			        {#date(2025,11,1), 1, 2, 1246075.07},
			        {#date(2025,11,1), 1, 3, 890053.62},
			        {#date(2025,11,1), 1, 4, 534032.17},
			        {#date(2025,12,1), 1, 1, 1881108.54},
			        {#date(2025,12,1), 1, 2, 1316775.98},
			        {#date(2025,12,1), 1, 3, 940554.27},
			        {#date(2025,12,1), 1, 4, 564332.56},
			        {#date(2025,1,1), 2, 1, 1157201.71},
			        {#date(2025,1,1), 2, 2, 810041.20},
			        {#date(2025,1,1), 2, 3, 578600.85},
			        {#date(2025,1,1), 2, 4, 347160.51},
			        {#date(2025,2,1), 2, 1, 1162883.43},
			        {#date(2025,2,1), 2, 2, 814018.40},
			        {#date(2025,2,1), 2, 3, 581441.72},
			        {#date(2025,2,1), 2, 4, 348865.03},
			        {#date(2025,3,1), 2, 1, 1240822.81},
			        {#date(2025,3,1), 2, 2, 868575.96},
			        {#date(2025,3,1), 2, 3, 620411.40},
			        {#date(2025,3,1), 2, 4, 372246.84},
			        {#date(2025,4,1), 2, 1, 1242026.00},
			        {#date(2025,4,1), 2, 2, 869418.20},
			        {#date(2025,4,1), 2, 3, 621013.00},
			        {#date(2025,4,1), 2, 4, 372607.80},
			        {#date(2025,5,1), 2, 1, 1315528.38},
			        {#date(2025,5,1), 2, 2, 920869.87},
			        {#date(2025,5,1), 2, 3, 657764.19},
			        {#date(2025,5,1), 2, 4, 394658.51},
			        {#date(2025,6,1), 2, 1, 1263907.12},
			        {#date(2025,6,1), 2, 2, 884734.98},
			        {#date(2025,6,1), 2, 3, 631953.56},
			        {#date(2025,6,1), 2, 4, 379172.13},
			        {#date(2025,7,1), 2, 1, 1141209.83},
			        {#date(2025,7,1), 2, 2, 798846.88},
			        {#date(2025,7,1), 2, 3, 570604.91},
			        {#date(2025,7,1), 2, 4, 342362.95},
			        {#date(2025,8,1), 2, 1, 1084233.26},
			        {#date(2025,8,1), 2, 2, 758963.28},
			        {#date(2025,8,1), 2, 3, 542116.63},
			        {#date(2025,8,1), 2, 4, 325269.98},
			        {#date(2025,9,1), 2, 1, 1275697.36},
			        {#date(2025,9,1), 2, 2, 892988.15},
			        {#date(2025,9,1), 2, 3, 637848.68},
			        {#date(2025,9,1), 2, 4, 382709.21},
			        {#date(2025,10,1), 2, 1, 1355599.43},
			        {#date(2025,10,1), 2, 2, 948919.60},
			        {#date(2025,10,1), 2, 3, 677799.72},
			        {#date(2025,10,1), 2, 4, 406679.83},
			        {#date(2025,11,1), 2, 1, 1420510.95},
			        {#date(2025,11,1), 2, 2, 994357.66},
			        {#date(2025,11,1), 2, 3, 710255.47},
			        {#date(2025,11,1), 2, 4, 426153.28},
			        {#date(2025,12,1), 2, 1, 1483210.29},
			        {#date(2025,12,1), 2, 2, 1038247.20},
			        {#date(2025,12,1), 2, 3, 741605.14},
			        {#date(2025,12,1), 2, 4, 444963.09},
			        {#date(2025,1,1), 3, 1, 822045.49},
			        {#date(2025,1,1), 3, 2, 575431.84},
			        {#date(2025,1,1), 3, 3, 411022.74},
			        {#date(2025,1,1), 3, 4, 246613.65},
			        {#date(2025,2,1), 3, 1, 843584.60},
			        {#date(2025,2,1), 3, 2, 590509.22},
			        {#date(2025,2,1), 3, 3, 421792.30},
			        {#date(2025,2,1), 3, 4, 253075.38},
			        {#date(2025,3,1), 3, 1, 924754.18},
			        {#date(2025,3,1), 3, 2, 647327.93},
			        {#date(2025,3,1), 3, 3, 462377.09},
			        {#date(2025,3,1), 3, 4, 277426.25},
			        {#date(2025,4,1), 3, 1, 932305.92},
			        {#date(2025,4,1), 3, 2, 652614.14},
			        {#date(2025,4,1), 3, 3, 466152.96},
			        {#date(2025,4,1), 3, 4, 279691.78},
			        {#date(2025,5,1), 3, 1, 969665.07},
			        {#date(2025,5,1), 3, 2, 678765.55},
			        {#date(2025,5,1), 3, 3, 484832.53},
			        {#date(2025,5,1), 3, 4, 290899.52},
			        {#date(2025,6,1), 3, 1, 907077.74},
			        {#date(2025,6,1), 3, 2, 634954.42},
			        {#date(2025,6,1), 3, 3, 453538.87},
			        {#date(2025,6,1), 3, 4, 272123.32},
			        {#date(2025,7,1), 3, 1, 809427.59},
			        {#date(2025,7,1), 3, 2, 566599.32},
			        {#date(2025,7,1), 3, 3, 404713.80},
			        {#date(2025,7,1), 3, 4, 242828.28},
			        {#date(2025,8,1), 3, 1, 780434.52},
			        {#date(2025,8,1), 3, 2, 546304.17},
			        {#date(2025,8,1), 3, 3, 390217.26},
			        {#date(2025,8,1), 3, 4, 234130.36},
			        {#date(2025,9,1), 3, 1, 944546.70},
			        {#date(2025,9,1), 3, 2, 661182.69},
			        {#date(2025,9,1), 3, 3, 472273.35},
			        {#date(2025,9,1), 3, 4, 283364.01},
			        {#date(2025,10,1), 3, 1, 1018391.33},
			        {#date(2025,10,1), 3, 2, 712873.93},
			        {#date(2025,10,1), 3, 3, 509195.66},
			        {#date(2025,10,1), 3, 4, 305517.40},
			        {#date(2025,11,1), 3, 1, 1054431.46},
			        {#date(2025,11,1), 3, 2, 738102.02},
			        {#date(2025,11,1), 3, 3, 527215.73},
			        {#date(2025,11,1), 3, 4, 316329.44},
			        {#date(2025,12,1), 3, 1, 1071940.51},
			        {#date(2025,12,1), 3, 2, 750358.36},
			        {#date(2025,12,1), 3, 3, 535970.25},
			        {#date(2025,12,1), 3, 4, 321582.15},
			        {#date(2025,1,1), 4, 1, 608363.36},
			        {#date(2025,1,1), 4, 2, 425854.35},
			        {#date(2025,1,1), 4, 3, 304181.68},
			        {#date(2025,1,1), 4, 4, 182509.01},
			        {#date(2025,2,1), 4, 1, 641386.66},
			        {#date(2025,2,1), 4, 2, 448970.66},
			        {#date(2025,2,1), 4, 3, 320693.33},
			        {#date(2025,2,1), 4, 4, 192416.00},
			        {#date(2025,3,1), 4, 1, 708155.77},
			        {#date(2025,3,1), 4, 2, 495709.04},
			        {#date(2025,3,1), 4, 3, 354077.89},
			        {#date(2025,3,1), 4, 4, 212446.73},
			        {#date(2025,4,1), 4, 1, 701059.23},
			        {#date(2025,4,1), 4, 2, 490741.46},
			        {#date(2025,4,1), 4, 3, 350529.62},
			        {#date(2025,4,1), 4, 4, 210317.77},
			        {#date(2025,5,1), 4, 1, 709946.87},
			        {#date(2025,5,1), 4, 2, 496962.81},
			        {#date(2025,5,1), 4, 3, 354973.43},
			        {#date(2025,5,1), 4, 4, 212984.06},
			        {#date(2025,6,1), 4, 1, 656344.36},
			        {#date(2025,6,1), 4, 2, 459441.05},
			        {#date(2025,6,1), 4, 3, 328172.18},
			        {#date(2025,6,1), 4, 4, 196903.31},
			        {#date(2025,7,1), 4, 1, 594383.16},
			        {#date(2025,7,1), 4, 2, 416068.21},
			        {#date(2025,7,1), 4, 3, 297191.58},
			        {#date(2025,7,1), 4, 4, 178314.95},
			        {#date(2025,8,1), 4, 1, 589504.32},
			        {#date(2025,8,1), 4, 2, 412653.03},
			        {#date(2025,8,1), 4, 3, 294752.16},
			        {#date(2025,8,1), 4, 4, 176851.30},
			        {#date(2025,9,1), 4, 1, 723904.86},
			        {#date(2025,9,1), 4, 2, 506733.40},
			        {#date(2025,9,1), 4, 3, 361952.43},
			        {#date(2025,9,1), 4, 4, 217171.46},
			        {#date(2025,10,1), 4, 1, 771193.22},
			        {#date(2025,10,1), 4, 2, 539835.25},
			        {#date(2025,10,1), 4, 3, 385596.61},
			        {#date(2025,10,1), 4, 4, 231357.97},
			        {#date(2025,11,1), 4, 1, 777429.56},
			        {#date(2025,11,1), 4, 2, 544200.69},
			        {#date(2025,11,1), 4, 3, 388714.78},
			        {#date(2025,11,1), 4, 4, 233228.87},
			        {#date(2025,12,1), 4, 1, 776216.06},
			        {#date(2025,12,1), 4, 2, 543351.24},
			        {#date(2025,12,1), 4, 3, 388108.03},
			        {#date(2025,12,1), 4, 4, 232864.82},
			        {#date(2025,1,1), 5, 1, 318857.99},
			        {#date(2025,1,1), 5, 2, 223200.59},
			        {#date(2025,1,1), 5, 3, 159428.99},
			        {#date(2025,1,1), 5, 4, 95657.40},
			        {#date(2025,2,1), 5, 1, 338583.19},
			        {#date(2025,2,1), 5, 2, 237008.23},
			        {#date(2025,2,1), 5, 3, 169291.59},
			        {#date(2025,2,1), 5, 4, 101574.96},
			        {#date(2025,3,1), 5, 1, 367086.18},
			        {#date(2025,3,1), 5, 2, 256960.33},
			        {#date(2025,3,1), 5, 3, 183543.09},
			        {#date(2025,3,1), 5, 4, 110125.86},
			        {#date(2025,4,1), 5, 1, 353835.81},
			        {#date(2025,4,1), 5, 2, 247685.06},
			        {#date(2025,4,1), 5, 3, 176917.90},
			        {#date(2025,4,1), 5, 4, 106150.74},
			        {#date(2025,5,1), 5, 1, 354124.57},
			        {#date(2025,5,1), 5, 2, 247887.20},
			        {#date(2025,5,1), 5, 3, 177062.29},
			        {#date(2025,5,1), 5, 4, 106237.37},
			        {#date(2025,6,1), 5, 1, 332248.64},
			        {#date(2025,6,1), 5, 2, 232574.05},
			        {#date(2025,6,1), 5, 3, 166124.32},
			        {#date(2025,6,1), 5, 4, 99674.59},
			        {#date(2025,7,1), 5, 1, 309499.53},
			        {#date(2025,7,1), 5, 2, 216649.67},
			        {#date(2025,7,1), 5, 3, 154749.76},
			        {#date(2025,7,1), 5, 4, 92849.86},
			        {#date(2025,8,1), 5, 1, 311449.77},
			        {#date(2025,8,1), 5, 2, 218014.84},
			        {#date(2025,8,1), 5, 3, 155724.89},
			        {#date(2025,8,1), 5, 4, 93434.93},
			        {#date(2025,9,1), 5, 1, 377896.59},
			        {#date(2025,9,1), 5, 2, 264527.61},
			        {#date(2025,9,1), 5, 3, 188948.29},
			        {#date(2025,9,1), 5, 4, 113368.98},
			        {#date(2025,10,1), 5, 1, 391966.43},
			        {#date(2025,10,1), 5, 2, 274376.50},
			        {#date(2025,10,1), 5, 3, 195983.21},
			        {#date(2025,10,1), 5, 4, 117589.93},
			        {#date(2025,11,1), 5, 1, 388075.26},
			        {#date(2025,11,1), 5, 2, 271652.68},
			        {#date(2025,11,1), 5, 3, 194037.63},
			        {#date(2025,11,1), 5, 4, 116422.58},
			        {#date(2025,12,1), 5, 1, 390348.97},
			        {#date(2025,12,1), 5, 2, 273244.28},
			        {#date(2025,12,1), 5, 3, 195174.49},
			        {#date(2025,12,1), 5, 4, 117104.69}
			    }, {"Date", "ProductKey", "RegionKey", "Amount"}),
			    Typed = Table.TransformColumnTypes(Source, {{"Date", type date}, {"ProductKey", Int64.Type}, {"RegionKey", Int64.Type}, {"Amount", type number}})
			in
			    Typed
