table FactActuals

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: Date

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey

	column RegionKey
		dataType: int64
		summarizeBy: none
		sourceColumn: RegionKey

	column Amount
		dataType: double
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Amount

	column Cost
		dataType: double
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Cost

	partition FactActuals = m
		mode: import
		source =
			let
			    Source = Table.FromRows({
			        {#date(2024,1,1), 1, 1, 1441503.05, 792826.68},
			        {#date(2025,1,1), 1, 1, 1587762.30, 873269.27},
			        {#date(2024,1,1), 1, 2, 1009052.14, 554978.68},
			        {#date(2025,1,1), 1, 2, 1111433.61, 611288.49},
			        {#date(2024,1,1), 1, 3, 720751.53, 396413.34},
			        {#date(2025,1,1), 1, 3, 793881.15, 436634.63},
			        {#date(2024,1,1), 1, 4, 432450.92, 237848.01},
			        {#date(2025,1,1), 1, 4, 476328.69, 261980.78},
			        {#date(2024,2,1), 1, 1, 1457057.57, 801381.66},
			        {#date(2025,2,1), 1, 1, 1602756.83, 881516.26},
			        {#date(2024,2,1), 1, 2, 1019940.30, 560967.17},
			        {#date(2025,2,1), 1, 2, 1121929.78, 617061.38},
			        {#date(2024,2,1), 1, 3, 728528.79, 400690.83},
			        {#date(2025,2,1), 1, 3, 801378.41, 440758.13},
			        {#date(2024,2,1), 1, 4, 437117.27, 240414.50},
			        {#date(2025,2,1), 1, 4, 480827.05, 264454.88},
			        {#date(2024,3,1), 1, 1, 1499483.00, 824715.65},
			        {#date(2025,3,1), 1, 1, 1674694.30, 921081.87},
			        {#date(2024,3,1), 1, 2, 1049638.10, 577300.96},
			        {#date(2025,3,1), 1, 2, 1172286.01, 644757.31},
			        {#date(2024,3,1), 1, 3, 749741.50, 412357.83},
			        {#date(2025,3,1), 1, 3, 837347.15, 460540.93},
			        {#date(2024,3,1), 1, 4, 449844.90, 247414.70},
			        {#date(2025,3,1), 1, 4, 502408.29, 276324.56},
			        {#date(2024,4,1), 1, 1, 1434797.48, 789138.61},
			        {#date(2025,4,1), 1, 1, 1631670.22, 897418.62},
			        {#date(2024,4,1), 1, 2, 1004358.23, 552397.03},
			        {#date(2025,4,1), 1, 2, 1142169.15, 628193.03},
			        {#date(2024,4,1), 1, 3, 717398.74, 394569.31},
			        {#date(2025,4,1), 1, 3, 815835.11, 448709.31},
			        {#date(2024,4,1), 1, 4, 430439.24, 236741.58},
			        {#date(2025,4,1), 1, 4, 489501.06, 269225.58},
			        {#date(2024,5,1), 1, 1, 1502666.71, 826466.69},
			        {#date(2025,5,1), 1, 1, 1715894.98, 943742.24},
			        {#date(2024,5,1), 1, 2, 1051866.70, 578526.69},
			        {#date(2025,5,1), 1, 2, 1201126.49, 660619.57},
			        {#date(2024,5,1), 1, 3, 751333.36, 413233.35},
			        {#date(2025,5,1), 1, 3, 857947.49, 471871.12},
			        {#date(2024,5,1), 1, 4, 450800.01, 247940.01},
			        {#date(2025,5,1), 1, 4, 514768.49, 283122.67},
			        {#date(2024,6,1), 1, 1, 1490596.38, 819828.01},
			        {#date(2025,6,1), 1, 1, 1678849.88, 923367.43},
			        {#date(2024,6,1), 1, 2, 1043417.47, 573879.61},
			        {#date(2025,6,1), 1, 2, 1175194.92, 646357.21},
			        {#date(2024,6,1), 1, 3, 745298.19, 409914.00},
			        {#date(2025,6,1), 1, 3, 839424.94, 461683.72},
			        {#date(2024,6,1), 1, 4, 447178.91, 245948.40},
			        {#date(2025,6,1), 1, 4, 503654.96, 277010.23},
			        {#date(2024,7,1), 1, 1, 1408334.14, 774583.78},
			        {#date(2025,7,1), 1, 1, 1556877.29, 856282.51},
			        {#date(2024,7,1), 1, 2, 985833.90, 542208.65},
			        {#date(2025,7,1), 1, 2, 1089814.10, 599397.76},
			        {#date(2024,7,1), 1, 3, 704167.07, 387291.89},
			        {#date(2025,7,1), 1, 3, 778438.65, 428141.26},
			        {#date(2024,7,1), 1, 4, 422500.24, 232375.13},
			        {#date(2025,7,1), 1, 4, 467063.19, 256884.75},
			        {#date(2024,8,1), 1, 1, 1362761.87, 749519.03},
			        {#date(2025,8,1), 1, 1, 1496678.28, 823173.05},
			        {#date(2024,8,1), 1, 2, 953933.31, 524663.32},
			        {#date(2025,8,1), 1, 2, 1047674.80, 576221.14},
			        {#date(2024,8,1), 1, 3, 681380.94, 374759.52},
			        {#date(2025,8,1), 1, 3, 748339.14, 411586.53},
			        {#date(2024,8,1), 1, 4, 408828.56, 224855.71},
			        {#date(2025,8,1), 1, 4, 449003.48, 246951.91},
			        {#date(2024,9,1), 1, 1, 1562064.86, 859135.67},
			        {#date(2025,9,1), 1, 1, 1735210.40, 954365.72},
			        {#date(2024,9,1), 1, 2, 1093445.41, 601394.98},
			        {#date(2025,9,1), 1, 2, 1214647.28, 668056.00},
			        {#date(2024,9,1), 1, 3, 781032.43, 429567.84},
			        {#date(2025,9,1), 1, 3, 867605.20, 477182.86},
			        {#date(2024,9,1), 1, 4, 468619.46, 257740.70},
			        {#date(2025,9,1), 1, 4, 520563.12, 286309.72},
			        {#date(2024,10,1), 1, 1, 1583086.36, 870697.50},
			        {#date(2024,10,1), 1, 2, 1108160.45, 609488.25},
			        {#date(2024,10,1), 1, 3, 791543.18, 435348.75},
			        {#date(2024,10,1), 1, 4, 474925.91, 261209.25},
			        {#date(2024,11,1), 1, 1, 1619897.91, 890943.85},
			        {#date(2024,11,1), 1, 2, 1133928.54, 623660.70},
			        {#date(2024,11,1), 1, 3, 809948.96, 445471.93},
			        {#date(2024,11,1), 1, 4, 485969.37, 267283.15},
			        {#date(2024,12,1), 1, 1, 1727998.54, 950399.20},
			        {#date(2024,12,1), 1, 2, 1209598.98, 665279.44},
			        {#date(2024,12,1), 1, 3, 863999.27, 475199.60},
			        {#date(2024,12,1), 1, 4, 518399.56, 285119.76},
			        {#date(2024,1,1), 2, 1, 1132489.37, 452995.75},
			        {#date(2025,1,1), 2, 1, 1145629.69, 458251.88},
			        {#date(2024,1,1), 2, 2, 792742.56, 317097.02},
			        {#date(2025,1,1), 2, 2, 801940.78, 320776.31},
			        {#date(2024,1,1), 2, 3, 566244.69, 226497.88},
			        {#date(2025,1,1), 2, 3, 572814.85, 229125.94},
			        {#date(2024,1,1), 2, 4, 339746.81, 135898.72},
			        {#date(2025,1,1), 2, 4, 343688.91, 137475.56},
			        {#date(2024,2,1), 2, 1, 1100805.00, 440322.00},
			        {#date(2025,2,1), 2, 1, 1151254.60, 460501.84},
			        {#date(2024,2,1), 2, 2, 770563.50, 308225.40},
			        {#date(2025,2,1), 2, 2, 805878.22, 322351.29},
			        {#date(2024,2,1), 2, 3, 550402.50, 220161.00},
			        {#date(2025,2,1), 2, 3, 575627.30, 230250.92},
			        {#date(2024,2,1), 2, 4, 330241.50, 132096.60},
			        {#date(2025,2,1), 2, 4, 345376.38, 138150.55},
			        {#date(2024,3,1), 2, 1, 1185970.70, 474388.28},
			        {#date(2025,3,1), 2, 1, 1228414.58, 491365.83},
			        {#date(2024,3,1), 2, 2, 830179.49, 332071.80},
			        {#date(2025,3,1), 2, 2, 859890.20, 343956.08},
			        {#date(2024,3,1), 2, 3, 592985.35, 237194.14},
			        {#date(2025,3,1), 2, 3, 614207.29, 245682.92},
			        {#date(2024,3,1), 2, 4, 355791.21, 142316.48},
			        {#date(2025,3,1), 2, 4, 368524.37, 147409.75},
			        {#date(2024,4,1), 2, 1, 1217413.74, 486965.50},
			        {#date(2025,4,1), 2, 1, 1229605.74, 491842.30},
			        {#date(2024,4,1), 2, 2, 852189.62, 340875.85},
			        {#date(2025,4,1), 2, 2, 860724.02, 344289.61},
			        {#date(2024,4,1), 2, 3, 608706.87, 243482.75},
			        {#date(2025,4,1), 2, 3, 614802.87, 245921.15},
			        {#date(2024,4,1), 2, 4, 365224.12, 146089.65},
			        {#date(2025,4,1), 2, 4, 368881.72, 147552.69},
			        {#date(2024,5,1), 2, 1, 1250682.26, 500272.90},
			        {#date(2025,5,1), 2, 1, 1302373.10, 520949.24},
			        {#date(2024,5,1), 2, 2, 875477.58, 350191.03},
			        {#date(2025,5,1), 2, 2, 911661.17, 364664.47},
			        {#date(2024,5,1), 2, 3, 625341.13, 250136.45},
			        {#date(2025,5,1), 2, 3, 651186.55, 260474.62},
			        {#date(2024,5,1), 2, 4, 375204.68, 150081.87},
			        {#date(2025,5,1), 2, 4, 390711.93, 156284.77},
			        {#date(2024,6,1), 2, 1, 1201786.52, 480714.61},
			        {#date(2025,6,1), 2, 1, 1251268.04, 500507.22},
			        {#date(2024,6,1), 2, 2, 841250.56, 336500.22},
			        {#date(2025,6,1), 2, 2, 875887.63, 350355.05},
			        {#date(2024,6,1), 2, 3, 600893.26, 240357.30},
			        {#date(2025,6,1), 2, 3, 625634.02, 250253.61},
			        {#date(2024,6,1), 2, 4, 360535.96, 144214.38},
			        {#date(2025,6,1), 2, 4, 375380.41, 150152.16},
			        {#date(2024,7,1), 2, 1, 1118622.76, 447449.10},
			        {#date(2025,7,1), 2, 1, 1129797.73, 451919.09},
			        {#date(2024,7,1), 2, 2, 783035.93, 313214.37},
			        {#date(2025,7,1), 2, 2, 790858.41, 316343.36},
			        {#date(2024,7,1), 2, 3, 559311.38, 223724.55},
			        {#date(2025,7,1), 2, 3, 564898.86, 225959.54},
			        {#date(2024,7,1), 2, 4, 335586.83, 134234.73},
			        {#date(2025,7,1), 2, 4, 338939.32, 135575.73},
			        {#date(2024,8,1), 2, 1, 1036126.47, 414450.59},
			        {#date(2025,8,1), 2, 1, 1073390.92, 429356.37},
			        {#date(2024,8,1), 2, 2, 725288.53, 290115.41},
			        {#date(2025,8,1), 2, 2, 751373.65, 300549.46},
			        {#date(2024,8,1), 2, 3, 518063.24, 207225.30},
			        {#date(2025,8,1), 2, 3, 536695.46, 214678.18},
			        {#date(2024,8,1), 2, 4, 310837.94, 124335.18},
			        {#date(2025,8,1), 2, 4, 322017.28, 128806.91},
			        {#date(2024,9,1), 2, 1, 1207739.17, 483095.67},
			        {#date(2025,9,1), 2, 1, 1262940.38, 505176.15},
			        {#date(2024,9,1), 2, 2, 845417.42, 338166.97},
			        {#date(2025,9,1), 2, 2, 884058.27, 353623.31},
			        {#date(2024,9,1), 2, 3, 603869.58, 241547.83},
			        {#date(2025,9,1), 2, 3, 631470.19, 252588.08},
			        {#date(2024,9,1), 2, 4, 362321.75, 144928.70},
			        {#date(2025,9,1), 2, 4, 378882.11, 151552.84},
			        {#date(2024,10,1), 2, 1, 1326745.32, 530698.13},
			        {#date(2024,10,1), 2, 2, 928721.72, 371488.69},
			        {#date(2024,10,1), 2, 3, 663372.66, 265349.06},
			        {#date(2024,10,1), 2, 4, 398023.60, 159209.44},
			        {#date(2024,11,1), 2, 1, 1365103.77, 546041.51},
			        {#date(2024,11,1), 2, 2, 955572.64, 382229.06},
			        {#date(2024,11,1), 2, 3, 682551.89, 273020.76},
			        {#date(2024,11,1), 2, 4, 409531.13, 163812.45},
			        {#date(2024,12,1), 2, 1, 1399789.86, 559915.94},
			        {#date(2024,12,1), 2, 2, 979852.90, 391941.16},
			        {#date(2024,12,1), 2, 3, 699894.93, 279957.97},
			        {#date(2024,12,1), 2, 4, 419936.96, 167974.78},
			        {#date(2024,1,1), 3, 1, 733545.69, 513481.98},
			        {#date(2025,1,1), 3, 1, 863147.76, 604203.43},
			        {#date(2024,1,1), 3, 2, 513481.98, 359437.39},
			        {#date(2025,1,1), 3, 2, 604203.43, 422942.40},
			        {#date(2024,1,1), 3, 3, 366772.84, 256740.99},
			        {#date(2025,1,1), 3, 3, 431573.88, 302101.72},
			        {#date(2024,1,1), 3, 4, 220063.71, 154044.60},
			        {#date(2025,1,1), 3, 4, 258944.33, 181261.03},
			        {#date(2024,2,1), 3, 1, 746452.47, 522516.73},
			        {#date(2025,2,1), 3, 1, 885763.83, 620034.68},
			        {#date(2024,2,1), 3, 2, 522516.73, 365761.71},
			        {#date(2025,2,1), 3, 2, 620034.68, 434024.28},
			        {#date(2024,2,1), 3, 3, 373226.23, 261258.36},
			        {#date(2025,2,1), 3, 3, 442881.92, 310017.34},
			        {#date(2024,2,1), 3, 4, 223935.74, 156755.02},
			        {#date(2025,2,1), 3, 4, 265729.15, 186010.40},
			        {#date(2024,3,1), 3, 1, 829656.92, 580759.84},
			        {#date(2025,3,1), 3, 1, 970991.89, 679694.32},
			        {#date(2024,3,1), 3, 2, 580759.84, 406531.89},
			        {#date(2025,3,1), 3, 2, 679694.32, 475786.02},
			        {#date(2024,3,1), 3, 3, 414828.46, 290379.92},
			        {#date(2025,3,1), 3, 3, 485495.95, 339847.16},
			        {#date(2024,3,1), 3, 4, 248897.08, 174227.96},
			        {#date(2025,3,1), 3, 4, 291297.57, 203908.30},
			        {#date(2024,4,1), 3, 1, 820691.49, 574484.04},
			        {#date(2025,4,1), 3, 1, 978921.21, 685244.85},
			        {#date(2024,4,1), 3, 2, 574484.05, 402138.84},
			        {#date(2025,4,1), 3, 2, 685244.85, 479671.39},
			        {#date(2024,4,1), 3, 3, 410345.75, 287242.02},
			        {#date(2025,4,1), 3, 3, 489460.61, 342622.43},
			        {#date(2024,4,1), 3, 4, 246207.45, 172345.21},
			        {#date(2025,4,1), 3, 4, 293676.36, 205573.45},
			        {#date(2024,5,1), 3, 1, 874059.42, 611841.59},
			        {#date(2025,5,1), 3, 1, 1018148.32, 712703.82},
			        {#date(2024,5,1), 3, 2, 611841.59, 428289.11},
			        {#date(2025,5,1), 3, 2, 712703.83, 498892.68},
			        {#date(2024,5,1), 3, 3, 437029.71, 305920.80},
			        {#date(2025,5,1), 3, 3, 509074.16, 356351.91},
			        {#date(2024,5,1), 3, 4, 262217.83, 183552.48},
			        {#date(2025,5,1), 3, 4, 305444.50, 213811.15},
			        {#date(2024,6,1), 3, 1, 795022.33, 556515.63},
			        {#date(2025,6,1), 3, 1, 952431.63, 666702.14},
			        {#date(2024,6,1), 3, 2, 556515.63, 389560.94},
			        {#date(2025,6,1), 3, 2, 666702.14, 466691.50},
			        {#date(2024,6,1), 3, 3, 397511.17, 278257.82},
			        {#date(2025,6,1), 3, 3, 476215.82, 333351.07},
			        {#date(2024,6,1), 3, 4, 238506.70, 166954.69},
			        {#date(2025,6,1), 3, 4, 285729.49, 200010.64},
			        {#date(2024,7,1), 3, 1, 732305.45, 512613.81},
			        {#date(2025,7,1), 3, 1, 849898.97, 594929.28},
			        {#date(2024,7,1), 3, 2, 512613.81, 358829.67},
			        {#date(2025,7,1), 3, 2, 594929.28, 416450.50},
			        {#date(2024,7,1), 3, 3, 366152.72, 256306.90},
			        {#date(2025,7,1), 3, 3, 424949.49, 297464.64},
			        {#date(2024,7,1), 3, 4, 219691.63, 153784.14},
			        {#date(2025,7,1), 3, 4, 254969.69, 178478.78},
			        {#date(2024,8,1), 3, 1, 681876.79, 477313.75},
			        {#date(2025,8,1), 3, 1, 819456.25, 573619.38},
			        {#date(2024,8,1), 3, 2, 477313.75, 334119.62},
			        {#date(2025,8,1), 3, 2, 573619.37, 401533.56},
			        {#date(2024,8,1), 3, 3, 340938.39, 238656.87},
			        {#date(2025,8,1), 3, 3, 409728.12, 286809.68},
			        {#date(2024,8,1), 3, 4, 204563.04, 143194.13},
			        {#date(2025,8,1), 3, 4, 245836.87, 172085.81},
			        {#date(2024,9,1), 3, 1, 856562.89, 599594.02},
			        {#date(2025,9,1), 3, 1, 991774.03, 694241.82},
			        {#date(2024,9,1), 3, 2, 599594.02, 419715.81},
			        {#date(2025,9,1), 3, 2, 694241.82, 485969.27},
			        {#date(2024,9,1), 3, 3, 428281.45, 299797.02},
			        {#date(2025,9,1), 3, 3, 495887.02, 347120.91},
			        {#date(2024,9,1), 3, 4, 256968.87, 179878.21},
			        {#date(2025,9,1), 3, 4, 297532.21, 208272.55},
			        {#date(2024,10,1), 3, 1, 888288.67, 621802.07},
			        {#date(2024,10,1), 3, 2, 621802.07, 435261.45},
			        {#date(2024,10,1), 3, 3, 444144.34, 310901.04},
			        {#date(2024,10,1), 3, 4, 266486.60, 186540.62},
			        {#date(2024,11,1), 3, 1, 957028.93, 669920.25},
			        {#date(2024,11,1), 3, 2, 669920.25, 468944.17},
			        {#date(2024,11,1), 3, 3, 478514.47, 334960.13},
			        {#date(2024,11,1), 3, 4, 287108.68, 200976.08},
			        {#date(2024,12,1), 3, 1, 934925.29, 654447.70},
			        {#date(2024,12,1), 3, 2, 654447.71, 458113.40},
			        {#date(2024,12,1), 3, 3, 467462.65, 327223.85},
			        {#date(2024,12,1), 3, 4, 280477.59, 196334.31},
			        {#date(2024,1,1), 4, 1, 599155.15, 617129.80},
			        {#date(2025,1,1), 4, 1, 571861.56, 589017.41},
			        {#date(2024,1,1), 4, 2, 419408.60, 431990.86},
			        {#date(2025,1,1), 4, 2, 400303.09, 412312.18},
			        {#date(2024,1,1), 4, 3, 299577.57, 308564.90},
			        {#date(2025,1,1), 4, 3, 285930.78, 294508.70},
			        {#date(2024,1,1), 4, 4, 179746.54, 185138.94},
			        {#date(2025,1,1), 4, 4, 171558.47, 176705.22},
			        {#date(2024,2,1), 4, 1, 654077.88, 673700.22},
			        {#date(2025,2,1), 4, 1, 602903.46, 620990.56},
			        {#date(2024,2,1), 4, 2, 457854.52, 471590.16},
			        {#date(2025,2,1), 4, 2, 422032.42, 434693.39},
			        {#date(2024,2,1), 4, 3, 327038.94, 336850.11},
			        {#date(2025,2,1), 4, 3, 301451.73, 310495.28},
			        {#date(2024,2,1), 4, 4, 196223.37, 202110.07},
			        {#date(2025,2,1), 4, 4, 180871.04, 186297.17},
			        {#date(2024,3,1), 4, 1, 700556.23, 721572.92},
			        {#date(2025,3,1), 4, 1, 665666.43, 685636.42},
			        {#date(2024,3,1), 4, 2, 490389.36, 505101.04},
			        {#date(2025,3,1), 4, 2, 465966.50, 479945.49},
			        {#date(2024,3,1), 4, 3, 350278.11, 360786.45},
			        {#date(2025,3,1), 4, 3, 332833.21, 342818.21},
			        {#date(2024,3,1), 4, 4, 210166.87, 216471.88},
			        {#date(2025,3,1), 4, 4, 199699.93, 205690.93},
			        {#date(2024,4,1), 4, 1, 697022.49, 717933.16},
			        {#date(2025,4,1), 4, 1, 658995.68, 678765.55},
			        {#date(2024,4,1), 4, 2, 487915.74, 502553.21},
			        {#date(2025,4,1), 4, 2, 461296.97, 475135.88},
			        {#date(2024,4,1), 4, 3, 348511.24, 358966.58},
			        {#date(2025,4,1), 4, 3, 329497.84, 339382.78},
			        {#date(2024,4,1), 4, 4, 209106.75, 215379.95},
			        {#date(2025,4,1), 4, 4, 197698.70, 203629.66},
			        {#date(2024,5,1), 4, 1, 722909.72, 744597.01},
			        {#date(2025,5,1), 4, 1, 667350.06, 687370.56},
			        {#date(2024,5,1), 4, 2, 506036.80, 521217.90},
			        {#date(2025,5,1), 4, 2, 467145.04, 481159.39},
			        {#date(2024,5,1), 4, 3, 361454.86, 372298.51},
			        {#date(2025,5,1), 4, 3, 333675.03, 343685.28},
			        {#date(2024,5,1), 4, 4, 216872.92, 223379.11},
			        {#date(2025,5,1), 4, 4, 200205.02, 206211.17},
			        {#date(2024,6,1), 4, 1, 644456.94, 663790.65},
			        {#date(2025,6,1), 4, 1, 616963.70, 635472.61},
			        {#date(2024,6,1), 4, 2, 451119.85, 464653.45},
			        {#date(2025,6,1), 4, 2, 431874.59, 444830.83},
			        {#date(2024,6,1), 4, 3, 322228.47, 331895.32},
			        {#date(2025,6,1), 4, 3, 308481.85, 317736.31},
			        {#date(2024,6,1), 4, 4, 193337.08, 199137.19},
			        {#date(2025,6,1), 4, 4, 185089.11, 190641.78},
			        {#date(2024,7,1), 4, 1, 597603.60, 615531.71},
			        {#date(2025,7,1), 4, 1, 558720.17, 575481.78},
			        {#date(2024,7,1), 4, 2, 418322.52, 430872.20},
			        {#date(2025,7,1), 4, 2, 391104.12, 402837.24},
			        {#date(2024,7,1), 4, 3, 298801.80, 307765.85},
			        {#date(2025,7,1), 4, 3, 279360.08, 287740.88},
			        {#date(2024,7,1), 4, 4, 179281.08, 184659.51},
			        {#date(2025,7,1), 4, 4, 167616.05, 172644.53},
			        {#date(2024,8,1), 4, 1, 596005.69, 613885.86},
			        {#date(2025,8,1), 4, 1, 554134.06, 570758.08},
			        {#date(2024,8,1), 4, 2, 417203.98, 429720.10},
			        {#date(2025,8,1), 4, 2, 387893.84, 399530.66},
			        {#date(2024,8,1), 4, 3, 298002.85, 306942.94},
			        {#date(2025,8,1), 4, 3, 277067.03, 285379.04},
			        {#date(2024,8,1), 4, 4, 178801.71, 184165.76},
			        {#date(2025,8,1), 4, 4, 166240.22, 171227.43},
			        {#date(2024,9,1), 4, 1, 709545.79, 730832.16},
			        {#date(2025,9,1), 4, 1, 680470.57, 700884.69},
			        {#date(2024,9,1), 4, 2, 496682.05, 511582.51},
			        {#date(2025,9,1), 4, 2, 476329.40, 490619.28},
			        {#date(2024,9,1), 4, 3, 354772.89, 365416.08},
			        {#date(2025,9,1), 4, 3, 340235.28, 350442.34},
			        {#date(2024,9,1), 4, 4, 212863.74, 219249.65},
			        {#date(2025,9,1), 4, 4, 204141.17, 210265.41},
			        {#date(2024,10,1), 4, 1, 782685.74, 806166.31},
			        {#date(2024,10,1), 4, 2, 547880.02, 564316.42},
			        {#date(2024,10,1), 4, 3, 391342.87, 403083.16},
			        {#date(2024,10,1), 4, 4, 234805.72, 241849.89},
			        {#date(2024,11,1), 4, 1, 777704.80, 801035.94},
			        {#date(2024,11,1), 4, 2, 544393.36, 560725.16},
			        {#date(2024,11,1), 4, 3, 388852.40, 400517.97},
			        {#date(2024,11,1), 4, 4, 233311.44, 240310.78},
			        {#date(2024,12,1), 4, 1, 764289.43, 787218.11},
			        {#date(2024,12,1), 4, 2, 535002.60, 551052.68},
			        {#date(2024,12,1), 4, 3, 382144.71, 393609.05},
			        {#date(2024,12,1), 4, 4, 229286.83, 236165.43},
			        {#date(2024,1,1), 5, 1, 328699.04, 262959.23},
			        {#date(2025,1,1), 5, 1, 328423.73, 262738.98},
			        {#date(2024,1,1), 5, 2, 230089.33, 184071.46},
			        {#date(2025,1,1), 5, 2, 229896.61, 183917.29},
			        {#date(2024,1,1), 5, 3, 164349.52, 131479.62},
			        {#date(2025,1,1), 5, 3, 164211.86, 131369.49},
			        {#date(2024,1,1), 5, 4, 98609.71, 78887.77},
			        {#date(2025,1,1), 5, 4, 98527.12, 78821.70},
			        {#date(2024,2,1), 5, 1, 351985.96, 281588.77},
			        {#date(2025,2,1), 5, 1, 348740.68, 278992.54},
			        {#date(2024,2,1), 5, 2, 246390.17, 197112.14},
			        {#date(2025,2,1), 5, 2, 244118.48, 195294.78},
			        {#date(2024,2,1), 5, 3, 175992.98, 140794.38},
			        {#date(2025,2,1), 5, 3, 174370.34, 139496.27},
			        {#date(2024,2,1), 5, 4, 105595.79, 84476.63},
			        {#date(2025,2,1), 5, 4, 104622.20, 83697.76},
			        {#date(2024,3,1), 5, 1, 390832.89, 312666.31},
			        {#date(2025,3,1), 5, 1, 378098.77, 302479.02},
			        {#date(2024,3,1), 5, 2, 273583.02, 218866.42},
			        {#date(2025,3,1), 5, 2, 264669.14, 211735.31},
			        {#date(2024,3,1), 5, 3, 195416.44, 156333.15},
			        {#date(2025,3,1), 5, 3, 189049.39, 151239.51},
			        {#date(2024,3,1), 5, 4, 117249.87, 93799.90},
			        {#date(2025,3,1), 5, 4, 113429.63, 90743.70},
			        {#date(2024,4,1), 5, 1, 378678.93, 302943.14},
			        {#date(2025,4,1), 5, 1, 364450.88, 291560.70},
			        {#date(2024,4,1), 5, 2, 265075.25, 212060.20},
			        {#date(2025,4,1), 5, 2, 255115.62, 204092.50},
			        {#date(2024,4,1), 5, 3, 189339.47, 151471.58},
			        {#date(2025,4,1), 5, 3, 182225.44, 145780.35},
			        {#date(2024,4,1), 5, 4, 113603.68, 90882.94},
			        {#date(2025,4,1), 5, 4, 109335.26, 87468.21},
			        {#date(2024,5,1), 5, 1, 371206.95, 296965.56},
			        {#date(2025,5,1), 5, 1, 364748.31, 291798.65},
			        {#date(2024,5,1), 5, 2, 259844.86, 207875.89},
			        {#date(2025,5,1), 5, 2, 255323.82, 204259.06},
			        {#date(2024,5,1), 5, 3, 185603.47, 148482.78},
			        {#date(2025,5,1), 5, 3, 182374.15, 145899.32},
			        {#date(2024,5,1), 5, 4, 111362.08, 89089.66},
			        {#date(2025,5,1), 5, 4, 109424.49, 87539.59},
			        {#date(2024,6,1), 5, 1, 342299.69, 273839.75},
			        {#date(2025,6,1), 5, 1, 342216.10, 273772.88},
			        {#date(2024,6,1), 5, 2, 239609.78, 191687.82},
			        {#date(2025,6,1), 5, 2, 239551.27, 191641.02},
			        {#date(2024,6,1), 5, 3, 171149.85, 136919.88},
			        {#date(2025,6,1), 5, 3, 171108.05, 136886.44},
			        {#date(2024,6,1), 5, 4, 102689.91, 82151.93},
			        {#date(2025,6,1), 5, 4, 102664.83, 82131.86},
			        {#date(2024,7,1), 5, 1, 322504.64, 258003.71},
			        {#date(2025,7,1), 5, 1, 318784.51, 255027.61},
			        {#date(2024,7,1), 5, 2, 225753.25, 180602.60},
			        {#date(2025,7,1), 5, 2, 223149.16, 178519.33},
			        {#date(2024,7,1), 5, 3, 161252.32, 129001.86},
			        {#date(2025,7,1), 5, 3, 159392.26, 127513.81},
			        {#date(2024,7,1), 5, 4, 96751.39, 77401.11},
			        {#date(2025,7,1), 5, 4, 95635.35, 76508.28},
			        {#date(2024,8,1), 5, 1, 332218.18, 265774.54},
			        {#date(2025,8,1), 5, 1, 320793.27, 256634.62},
			        {#date(2024,8,1), 5, 2, 232552.72, 186042.18},
			        {#date(2025,8,1), 5, 2, 224555.29, 179644.23},
			        {#date(2024,8,1), 5, 3, 166109.09, 132887.27},
			        {#date(2025,8,1), 5, 3, 160396.63, 128317.30},
			        {#date(2024,8,1), 5, 4, 99665.45, 79732.36},
			        {#date(2025,8,1), 5, 4, 96237.98, 76990.38},
			        {#date(2024,9,1), 5, 1, 403936.21, 323148.97},
			        {#date(2025,9,1), 5, 1, 389233.49, 311386.79},
			        {#date(2024,9,1), 5, 2, 282755.35, 226204.28},
			        {#date(2025,9,1), 5, 2, 272463.44, 217970.75},
			        {#date(2024,9,1), 5, 3, 201968.11, 161574.49},
			        {#date(2025,9,1), 5, 3, 194616.74, 155693.39},
			        {#date(2024,9,1), 5, 4, 121180.86, 96944.69},
			        {#date(2025,9,1), 5, 4, 116770.05, 93416.04},
			        {#date(2024,10,1), 5, 1, 409802.93, 327842.34},
			        {#date(2024,10,1), 5, 2, 286862.05, 229489.64},
			        {#date(2024,10,1), 5, 3, 204901.47, 163921.18},
			        {#date(2024,10,1), 5, 4, 122940.88, 98352.70},
			        {#date(2024,11,1), 5, 1, 399719.52, 319775.62},
			        {#date(2024,11,1), 5, 2, 279803.66, 223842.93},
			        {#date(2024,11,1), 5, 3, 199859.76, 159887.81},
			        {#date(2024,11,1), 5, 4, 119915.86, 95932.69},
			        {#date(2024,12,1), 5, 1, 407763.68, 326210.94},
			        {#date(2024,12,1), 5, 2, 285434.57, 228347.66},
			        {#date(2024,12,1), 5, 3, 203881.84, 163105.47},
			        {#date(2024,12,1), 5, 4, 122329.10, 97863.28}
			    }, {"Date", "ProductKey", "RegionKey", "Amount", "Cost"}),
			    Typed = Table.TransformColumnTypes(Source, {{"Date", type date}, {"ProductKey", Int64.Type}, {"RegionKey", Int64.Type}, {"Amount", type number}, {"Cost", type number}})
			in
			    Typed
