table FactDaily

	column Day
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: Day

	column KPI
		dataType: string
		summarizeBy: none
		sourceColumn: KPI

	column Value
		dataType: double
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Value

	column ValuePY
		dataType: double
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: ValuePY

	partition FactDaily = m
		mode: import
		source =
			let
			    Source = Table.FromRows({
			        {#date(2025,12,2), "Orders", 17300000.00, 16168224.30},
			        {#date(2025,12,2), "Revenue", 11400000.00, 10654205.61},
			        {#date(2025,12,3), "Orders", 18382739.01, 17180129.92},
			        {#date(2025,12,3), "Revenue", 12010881.20, 11225122.62},
			        {#date(2025,12,4), "Orders", 19257083.29, 17997274.10},
			        {#date(2025,12,4), "Revenue", 12484438.70, 11667699.72},
			        {#date(2025,12,5), "Orders", 19773164.15, 18479592.66},
			        {#date(2025,12,5), "Revenue", 12721915.10, 11889640.28},
			        {#date(2025,12,6), "Orders", 19879541.52, 18579010.77},
			        {#date(2025,12,6), "Revenue", 12689413.49, 11859264.94},
			        {#date(2025,12,7), "Orders", 19632024.13, 18347686.10},
			        {#date(2025,12,7), "Revenue", 12423709.54, 11610943.50},
			        {#date(2025,12,8), "Orders", 19169214.41, 17915153.65},
			        {#date(2025,12,8), "Revenue", 12016136.66, 11230034.26},
			        {#date(2025,12,9), "Orders", 18663517.76, 17442539.96},
			        {#date(2025,12,9), "Revenue", 11580303.03, 10822713.11},
			        {#date(2025,12,10), "Orders", 18264303.44, 17069442.46},
			        {#date(2025,12,10), "Revenue", 11214636.95, 10480969.11},
			        {#date(2025,12,11), "Orders", 18052222.11, 16871235.61},
			        {#date(2025,12,11), "Revenue", 10972283.93, 10254470.96},
			        {#date(2025,12,12), "Orders", 18019623.96, 16840770.05},
			        {#date(2025,12,12), "Revenue", 10848203.07, 10138507.54},
			        {#date(2025,12,13), "Orders", 18082973.78, 16899975.50},
			        {#date(2025,12,13), "Revenue", 10787348.04, 10081633.68},
			        {#date(2025,12,14), "Orders", 18122192.60, 16936628.59},
			        {#date(2025,12,14), "Revenue", 10710591.65, 10009898.74},
			        {#date(2025,12,15), "Orders", 18032674.68, 16852966.99},
			        {#date(2025,12,15), "Revenue", 10549002.97, 9858881.28},
			        {#date(2025,12,16), "Orders", 17771432.35, 16608815.28},
			        {#date(2025,12,16), "Revenue", 10274254.84, 9602107.33},
			        {#date(2025,12,17), "Orders", 17380855.84, 16243790.50},
			        {#date(2025,12,17), "Revenue", 9914280.72, 9265682.92},
			        {#date(2025,12,18), "Orders", 16981253.04, 15870329.94},
			        {#date(2025,12,18), "Revenue", 9548358.65, 8923699.67},
			        {#date(2025,12,19), "Orders", 16734058.06, 15639306.59},
			        {#date(2025,12,19), "Revenue", 9282867.16, 8675576.78},
			        {#date(2025,12,20), "Orders", 16787743.72, 15689480.11},
			        {#date(2025,12,20), "Revenue", 9215643.84, 8612751.25},
			        {#date(2025,12,21), "Orders", 17224603.51, 16097760.29},
			        {#date(2025,12,21), "Revenue", 9400916.76, 8785903.52},
			        {#date(2025,12,22), "Orders", 18026594.05, 16847284.16},
			        {#date(2025,12,22), "Revenue", 9826796.08, 9183921.57},
			        {#date(2025,12,23), "Orders", 19072312.20, 17824590.84},
			        {#date(2025,12,23), "Revenue", 10413282.03, 9732039.28},
			        {#date(2025,12,24), "Orders", 20166951.10, 18847617.85},
			        {#date(2025,12,24), "Revenue", 11032004.77, 10310284.83},
			        {#date(2025,12,25), "Orders", 21096154.43, 19716032.17},
			        {#date(2025,12,25), "Revenue", 11541712.17, 10786646.88},
			        {#date(2025,12,26), "Orders", 21686725.22, 20267967.50},
			        {#date(2025,12,26), "Revenue", 11828274.42, 11054462.08},
			        {#date(2025,12,27), "Orders", 21854815.72, 20425061.42},
			        {#date(2025,12,27), "Revenue", 11836439.26, 11062092.77},
			        {#date(2025,12,28), "Orders", 21626313.03, 20211507.50},
			        {#date(2025,12,28), "Revenue", 11583265.23, 10825481.53},
			        {#date(2025,12,29), "Orders", 21123278.60, 19741381.87},
			        {#date(2025,12,29), "Revenue", 11149185.90, 10419799.91},
			        {#date(2025,12,30), "Orders", 20521442.75, 19178918.45},
			        {#date(2025,12,30), "Revenue", 10650000.42, 9953271.42},
			        {#date(2025,12,31), "Orders", 19993177.01, 18685212.15},
			        {#date(2025,12,31), "Revenue", 10199294.67, 9532051.10}
			    }, {"Day", "KPI", "Value", "ValuePY"}),
			    Typed = Table.TransformColumnTypes(Source, {{"Day", type date}, {"KPI", type text}, {"Value", type number}, {"ValuePY", type number}})
			in
			    Typed
