table FactForecast

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: Date

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey

	column RegionKey
		dataType: int64
		summarizeBy: none
		sourceColumn: RegionKey

	column Amount
		dataType: double
		formatString: #,##0
		summarizeBy: sum
		sourceColumn: Amount

	partition FactForecast = m
		mode: import
		source =
			let
			    Source = Table.FromRows({
			        {#date(2025,10,1), 1, 1, 1854196.26},
			        {#date(2025,10,1), 1, 2, 1297937.38},
			        {#date(2025,10,1), 1, 3, 927098.13},
			        {#date(2025,10,1), 1, 4, 556258.88},
			        {#date(2025,11,1), 1, 1, 1887908.92},
			        {#date(2025,11,1), 1, 2, 1321536.24},
			        {#date(2025,11,1), 1, 3, 943954.46},
			        {#date(2025,11,1), 1, 4, 566372.68},
			        {#date(2025,12,1), 1, 1, 1938477.91},
			        {#date(2025,12,1), 1, 2, 1356934.53},
			        {#date(2025,12,1), 1, 3, 969238.95},
			        {#date(2025,12,1), 1, 4, 581543.37},
			        {#date(2025,10,1), 2, 1, 1349542.01},
			        {#date(2025,10,1), 2, 2, 944679.41},
			        {#date(2025,10,1), 2, 3, 674771.00},
			        {#date(2025,10,1), 2, 4, 404862.60},
			        {#date(2025,11,1), 2, 1, 1374079.14},
			        {#date(2025,11,1), 2, 2, 961855.40},
			        {#date(2025,11,1), 2, 3, 687039.57},
			        {#date(2025,11,1), 2, 4, 412223.74},
			        {#date(2025,12,1), 2, 1, 1410884.83},
			        {#date(2025,12,1), 2, 2, 987619.38},
			        {#date(2025,12,1), 2, 3, 705442.41},
			        {#date(2025,12,1), 2, 4, 423265.45},
			        {#date(2025,10,1), 3, 1, 1059781.40},
			        {#date(2025,10,1), 3, 2, 741846.98},
			        {#date(2025,10,1), 3, 3, 529890.70},
			        {#date(2025,10,1), 3, 4, 317934.42},
			        {#date(2025,11,1), 3, 1, 1079050.15},
			        {#date(2025,11,1), 3, 2, 755335.11},
			        {#date(2025,11,1), 3, 3, 539525.08},
			        {#date(2025,11,1), 3, 4, 323715.05},
			        {#date(2025,12,1), 3, 1, 1107953.28},
			        {#date(2025,12,1), 3, 2, 775567.30},
			        {#date(2025,12,1), 3, 3, 553976.64},
			        {#date(2025,12,1), 3, 4, 332385.98},
			        {#date(2025,10,1), 4, 1, 727131.41},
			        {#date(2025,10,1), 4, 2, 508991.98},
			        {#date(2025,10,1), 4, 3, 363565.70},
			        {#date(2025,10,1), 4, 4, 218139.42},
			        {#date(2025,11,1), 4, 1, 740351.98},
			        {#date(2025,11,1), 4, 2, 518246.38},
			        {#date(2025,11,1), 4, 3, 370175.99},
			        {#date(2025,11,1), 4, 4, 222105.59},
			        {#date(2025,12,1), 4, 1, 760182.83},
			        {#date(2025,12,1), 4, 2, 532127.98},
			        {#date(2025,12,1), 4, 3, 380091.42},
			        {#date(2025,12,1), 4, 4, 228054.85},
			        {#date(2025,10,1), 5, 1, 415923.78},
			        {#date(2025,10,1), 5, 2, 291146.65},
			        {#date(2025,10,1), 5, 3, 207961.89},
			        {#date(2025,10,1), 5, 4, 124777.14},
			        {#date(2025,11,1), 5, 1, 423486.03},
			        {#date(2025,11,1), 5, 2, 296440.22},
			        {#date(2025,11,1), 5, 3, 211743.02},
			        {#date(2025,11,1), 5, 4, 127045.81},
			        {#date(2025,12,1), 5, 1, 434829.41},
			        {#date(2025,12,1), 5, 2, 304380.59},
			        {#date(2025,12,1), 5, 3, 217414.71},
			        {#date(2025,12,1), 5, 4, 130448.82}
			    }, {"Date", "ProductKey", "RegionKey", "Amount"}),
			    Typed = Table.TransformColumnTypes(Source, {{"Date", type date}, {"ProductKey", Int64.Type}, {"RegionKey", Int64.Type}, {"Amount", type number}})
			in
			    Typed
